version: 0.0
Resources:
    - TargetService:
          Type: AWS::ECS::Service
          Properties:
              TaskDefinition: "arn:aws:ecs:us-east-1:596059741778:task-definition/3big-api-srv:0"
              LoadBalancerInfo:
                  ContainerName: "3big-api-srv"
                  ContainerPort: 4000
